### ISSUE TITLE
BigWig2Bed.pl issue

### ISSUE THREAD

**Issue by yuhongning** [CancerGenome/rn5_mappability#1]
Dear developer,
Your script is exactly what I am looking for to convert mappability bigwig file to bed file, however, when I tried to convert a downloaded bigwig file (http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/), it errored out on each line "Argument .... isn't numeric in addition (or multiplication) ...". Does the expected input file a "bigwig" or other type of file?

Thanks,

yuhong ning

**Comment by CancerGenome** [comment]
Hi Yuhong,

I think bigwig file has a different format with wig file. The wig file here is generated by gem-2-wig. 

See this command line: 
gem-2-wig -I rn5.index.gem -i rn5_100.mappability -o rn5_100 # create wig file based on raw ASCII Score
./BigWig2Bed.pl rn5_100.wig | bgzip -c > rn5_100.wig.mapQ.gz # use inhouse tool, covert BigWig format to Bed and bgzip for tabix index.

**Comment by yuhongning** [comment]
Thanks, Yu.
I also found a R package to do the conversion.

Best regards,

Yuhong
